# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "v4l2loopback" ];
  boot.extraModulePackages = [ pkgs.linuxPackages_latest.v4l2loopback ];
  # allow ip forwarding for tailscale 
  boot.kernel.sysctl = {
    "net.ipv4.ip_forward" = 1;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b8a6a737-ddb5-4044-bf3a-0941d89a4584";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress=zstd:3" ];
    };

  fileSystems."/mnt/SSD" =
    { device = "/dev/disk/by-uuid/1941ad1d-9288-4040-9b04-95c2fba216a8";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b15758dc-d50b-40e8-8108-dc127e91a5c9";
      fsType = "btrfs";
      options = [ "compress=zstd:3"  ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2F62-8A73";
      fsType = "vfat";
    };

  # Plex Server Mount
  services.rpcbind.enable = true;
  boot.supportedFilesystems = [ "nfs" ]; # https://github.com/NixOS/nixpkgs/issues/76671
  systemd.mounts = [{
    type = "nfs";
    mountConfig = {
        Options = "noatime,vers=3";
    };
    what = "10.0.5.210:/mnt/plex-storage";
    where = "/mnt/plex";
  }];
  systemd.automounts = [{
    wantedBy = ["multi-user.target"];
    automountConfig = {
        TimeoutIdleSec = "600";
    };
    where = "/mnt/plex";
  }];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/004e8f6f-15b2-4beb-8f63-d769ede4918c"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp14s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
