# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

var:
  Empty: ""
secondary_prompt:
  template: "❯❯ "
  foreground: lightCyan
  background: transparent
transient_prompt:
  template: "❯ "
  foreground: blue
  background: transparent
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
      style: full
    template: <magenta>{{ .UserName }}</> <white>at</> <cyan>{{ .HostName }}</> <white>in</> <green>{{ .Path }}</> <yellow>{{ if or (eq .Env.IN_NIX_SHELL `impure`) (eq .Env.IN_NIX_SHELL `pure`) }}[ 󱄅 {{ .Env.NIX_SHELL_PACKAGES }} ]{{ end }}</>
    background: transparent
    type: path
    style: plain
  - properties:
      branch_icon: ""
      cache_duration: none
      fetch_upstream_icon: true
    template: " <darkGray>{{ .UpstreamIcon }}{{ .HEAD }}</>{{ if .Working.Changed }}<red>●</>{{ end }}{{ if .Staging.Changed }}<green>●</>{{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"
    background: transparent
    type: git
    style: plain
  newline: true
- type: rprompt
  overflow: hidden
  segments:
  - properties:
      cache_duration: none
      style: austin
      threshold: 1000
    foreground: yellow
    background: transparent
    type: executiontime
    style: plain
- type: prompt
  alignment: left
  segments:
  - properties:
      cache_duration: none
    template: "❯ "
    background: transparent
    type: text
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}red{{ end }}"
    - "{{ if eq .Code 0 }}blue{{ end }}"
  newline: true
version: 3
final_space: true
